# Docker-compose

version: '3.8'  # Utilise la version souhaitée

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app_compose_val:latest 
    ports:
      - "8506:8506"  # Redirige le port 8503 du conteneur vers le port 8503 de l'hôte
    environment:
      - no_proxy=localhost,127.0.0
      - https_proxy=http://
      - http_proxy=http://D
    volumes:
      - ./app:/app/app  # Monte le dossier app
      - ./modele_langdetect:/app/modele_langdetect
      - ./logs:/app/logs  # Monte le dossier logs pour les logs de l'application
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"