# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for runs with userManagedDependencies=False.

# Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: project_environment
dependencies:
  # The python interpreter version.
  # Currently Azure ML only supports 3.8 and later.
- python=3.9.19

- pip:
  - azureml-train-automl-runtime==1.57.0
  - inference-schema
  - xgboost<=1.5.2
  - azureml-interpret==1.57.0
  - azureml-defaults==1.57.0
- numpy==1.23.5
- pandas==1.3.5
- scikit-learn==1.5.1
- prophet==1.1.4
- holidays==0.54
- psutil==5.9.3
channels:
- anaconda
- conda-forge
